### ISSUE TITLE
rmote

### ISSUE THREAD

**Issue by wrathematics** [RBigData/remoter#18]
@snoweye: rmote is not available on CRAN, and produces a NOTE during R CMD check. Do you know the policy on this with CRAN? Isn't there some other DESCRIPTION field that has to be set for package dependencies that are unavailable on CRAN?

**Comment by snoweye** [comment]
You may drop that enhance at the moment. I believe CRAN will take that NOTE. I saw some packages did that for archived packages and not CRAN available packages.

@hafen does not give a date when `rmote` will go on CRAN. FYI #https://github.com/cloudyr/rmote/pull/5 .
