### ISSUE TITLE
cpm problem

### ISSUE THREAD

**Issue by snoweye** [RBigData/remoter#19]
FYI [cpm branch](https://github.com/snoweye/remoter/tree/obtain_server_cpm).
The very first try for cpm. It looks work for `cat()` and `print()`, but not `message()`. I test it with
```
a <- function(){ cat("aa"); print("bb"); message("cc"); return(1) }
a()
```
The down site is for debugging... can not print to server terminal anymore ... 

The `message()` redirect to `stderr` in batch mode instead of `stdout` in GUI? Or, the other around?

**Comment by wrathematics** [comment]
What do you mean by cpm?

At any rate, this solution makes no sense. The value `.pbdenv$status$ret` *is* the information presented to the client. And anyway, I told you that `capture.output()` won't work; you have to use those R_ext things that gui's use.
