### ISSUE TITLE
possible to tunnel through ssh relay

### ISSUE THREAD

**Issue by rmflight** [RBigData/remoter#21]
We have a rather unique setup.

A gateway machine that takes ssh connections on a non-standard port (8674)

Machines behind the gateway that take usual ssh connections.

So the normal way we connect to a remote machine behind our gateway is:

```
ssh -P user@gateway
ssh user@internalMachine
```

The gateway machine does not have `R` installed (and the sysadmin won't install it, I'm sure), so the section on relays in the vignette is not much help.

I have been able to set up ssh forwarding through gateway by adding in my local `.ssh/config`:

```
Host internalMachine
   ProxyCommand ssh -p 8674 user@gateway -W %h:%p
```

And then doing 

```
ssh internalMachine
```

I am thinking that I should be able to something similar to allow forwarding a port connection through the ssh connection on the `gateway`, but my understanding of ssh is rather limited in this regard.

I'd appreciate any pointers, as the documentation in `ssh` on `ssh -L` and `ssh -W` is not helping me very much at the moment.

**Comment by wrathematics** [comment]
How about:

```
ssh -A -t -p 8674 user@gateway -L 55555:localhost:55555 ssh -A -t internalMachine -L 55555:localhost:55555 "module load R \&\& Rscript -e 'remoter::server\(\)'"
```

(drop the `module load` if it's not that kind of setup; re-run with `-v` to see what's going on if it fails).  Then on your laptop run

```r
remoter::client()
```

We actually want to develop some utilities to simplify this at some point, but so far haven't spent a lot of time thinking about it.

**Comment by rmflight** [comment]
Wow! It worked. 

That is awesome, because now I get passing via `<Ctrl>+<enter>` from RStudio to my remote session  instead of copying and pasting commands to a tmux window.

**Comment by wrathematics** [comment]
Great to hear it! Let us know if you run into any other problems.
