### ISSUE TITLE
q.server in exit doesn't seem to work correctly

### ISSUE THREAD

**Issue by rmflight** [RBigData/remoter#23]
v 0.3.2

Start a remote, connect with a client

I expect that

```r
exit(client.only = FALSE, q.server = FALSE)
```

to stop my client, and then stop the server, without actually exiting `R` itself on the remote. However, this is not the behavior I see.

Everytime I use

```r
exit(client.only = FALSE, ...)
```

The remote `R` session is quit completely.

**Comment by rmflight** [comment]
Also, the only way I can stop the server without killing the `R` session is by doing <Ctrl>+c in the window that has the `server` session running. This keeps the `R` session alive.

**Comment by snoweye** [comment]
Have you tried `shutdown()`?

**Comment by rmflight** [comment]
Is that in a newer version? Not in 0.3.2

**Comment by snoweye** [comment]
I am not sure. You probably need to get it from the RBigData or my repo.

**Comment by rmflight** [comment]
Upgraded to github v 0.4.0, and `shutdown()` does a complete shutdown of both server and client. Not what I want to happen.

I want my client to stop, and the server to stop being a server, and just go back to being an `R` session.

`exit(q.server = TRUE)` still doesn't stop the remote server, btw.

**Comment by snoweye** [comment]
- The server is currently in a batch mode, so what you want to do then?
- I did propose an interactive mode version, but it is not tested yet.
