### ISSUE TITLE
relationship of `remoter` and `rmote`

### ISSUE THREAD

**Issue by rmflight** [RBigData/remoter#24]
Is it possible to use `remoter` and `rmote` together to enable passing commands without copying/pasting and viewing results on a local web-page?

An example here or on the `rmote` page would be awesome!

**Comment by snoweye** [comment]
Have you tried `shutdown()`?

**Comment by snoweye** [comment]
I did test with something like
```
remoter::client()
library(rmote)
### Open a local browser and point
start_rmote()
plot(1:5)
dev.off()
stop_rmote()
shutdown()
```

**Comment by rmflight** [comment]
Thanks! Will give it a try.

**Comment by snoweye** [comment]
Please let me know how this goes. I am not sure your `server.ip` should be your gateway or internal machine. You may need to forward the port as well.
