### ISSUE TITLE
when quitting over ssh, get connection refused

### ISSUE THREAD

**Issue by rmflight** [RBigData/remoter#25]
So the first couple of days I used `remoter`, it worked flawlessly, even with the tunneling over ssh. However, the last few times, when I quit the R `remoter::server()` session, I start getting this message:

```
channel 3: open failed: connect failed: Connection refused
```

I can only seem to stop it by rebooting the machine.

I connected to the server using:

```
ssh user@remote -L 55555:localhost:55555
```

I quit the server using 

```
remoter::exit(client.only = FALSE)
```

Both machines running Fedora 22, R 3.3.1, remoter v 0.3.2. Have also tried with remoter v 0.4.0, and still happens.

**Comment by wrathematics** [comment]
The error is an ssh one; I think it should be independent of R/remoter/etc. Could you try running the ssh tunnel with `-v` (for verbose), and see if there's anything interesting in the output? Feel free to paste it here if there's no protected information (machine names, etc).

**Comment by wrathematics** [comment]
[This thread](https://serverfault.com/questions/489192/ssh-tunnel-refusing-connections-with-channel-2-open-failed) suggests replacing the literal `localhost` with `127.0.0.1` in the tunnel. Might be worth a shot.

**Comment by snoweye** [comment]
- I can not recreate the error message with my local windows connecting to local Linux vm. I use my branch to test this. I think I did not touch anything related to tunnel nor forwarding nor `ssh`.
- The only problem I can think of is launch two servers at the same port. I may not see the zmq error message returned from server. I have no solution for this, but I doubt this was the reason.
- It looks like a `ssh` problem to me, but I can not believe `localhost` was the reason either...

**Comment by rmflight** [comment]
Right, it was really odd in that last week when I tried everything over
SSH, it all seemed to work. I will look at my sudoer logs and see if I
upgraded ssh since then.

I would have suspected multiple servers at same port, except when I get
this message I am rebooting the server machine.

It is odd, initial testing and use would show a client connect error when
starting a new server after shutting down an old one. But it would only
show a couple of messages, then connect.

This is odd because it happens when I shut off the remote server only.

Will try with verbose on ssh first thing tomorrow.

**Comment by wrathematics** [comment]
Did you ever get a chance to try this again? No worries if not; just curious.

**Comment by rmflight** [comment]
Unfortunately not, been running flat out. Want to get to it, as it is much
easier than my usual workflow.

Will report when I do.

**Comment by howff** [comment]
I know this issue has been closed but it's still an ongoing problem.

If a client is not shut down cleanly (exact circumstances to be determined) then the next time a ssh tunnel is created the session will fill with error messages `"channel 3: open failed: connect failed: Connection refused"` 

There is no indication to the user what is causing these errors but my investigations suggest they are caused by a background R remoter::client process.
