### ISSUE TITLE
remoter with Rstudio

### ISSUE THREAD

**Issue by inquil** [RBigData/remoter#26]
Hi,
not a bug in itself. 
a)Sometimes i need to cancel a command in the console of Rstudio while using remoter to connect to my institution cluster. The problem is that I found impossible to stop or cancel a command, the console in R studio does not do anything as if it hangs. The only solution I have is to kill manually the rsession program launched by Rstudio in order to relaunch remoter. 
b) any possibility to delete the warning messages, they keep appering from previous commands
c) By the way, great package, it helps me a lot to use Rstudio using a session in a remote server. It would be interesting if it could have a better integration with Rstudio to have the environment also sync'ed with the remote server. Anyway, quite useful!

Best regards,

Carlos

**Comment by wrathematics** [comment]
Hi, thanks for the report.

The interrupt handling wasn't working correctly (leading to eternal continuation lines). The latest push (https://github.com/RBigData/remoter/commit/908287b20764500806a8392483037fd29191f40a) should help if you get break out of `remoter+` lines.  If that's not what you mean, then I might need some more information to help diagnose the problem.

I think we fixed the repeated warning message problem already, but haven't sent that change off to CRAN.  We're planning a CRAN release of the latest (quite a bit has changed) relatively soon.  In the meantime, you might consider installing the github version.

Syncing the environment is an interesting idea; do you mean something like

```r
remoter> sync()
```

And all server objects automatically become local ones?  I don't think it would be hard to implement this, but for large objects, it could take quite a while to run.
