### ISSUE TITLE
Feature Request: Bind to an available port

### ISSUE THREAD

**Issue by iagomez** [RBigData/remoter#27]
It would be awesome if the `remoter::server()` had the ability to automatically find an open port.

In other languages a common way of doing this is by passing `port = 0`

Currently, I'm using this code as a workaroud:

````R
remoter::server(port = pbdZMQ::random_open_port())
````

But I'm getting this error message on the console:
> R_zmq_socket_close errno: 88 strerror: Socket operation on non-socket
> R_zmq_ctx_destroy errno: 14 strerror: Bad address

**Comment by wrathematics** [comment]
Thanks for the suggestion.

The messages are actually harmless, but I've added that to a few other fixes in a pbdZMQ PR. I've added the `server(port=0)` functionality in the github version. It prints the port being used while the server spins up. Eventually if we get [getip](https://github.com/wrathematics/getip) on CRAN, then we'll also print the local and external ip addresses.
