### ISSUE TITLE
Using `batch`

### ISSUE THREAD

**Issue by seblamydlc** [RBigData/remoter#32]
Hi,

I saw that you implemented a `batch` fonction to send code to the server without opening the REPL.
I get the following error when trying to use it:
`error in if (get.status(need_auto_rpng_off)) auto_rpng_off_local(get.status(ret)) : 
argument is of length zero`
I guess you are still working on it. But please let me know if you are able to make a quick fix. This function will be definitely very useful.
The whole pbdR project is really great and pbdCS and remoter are definitely a huge addition to the suite. Thanks!

**Comment by seblamydlc** [comment]
It seems to be a problem of R version. I upgraded to 3.3.1 and it worked

**Comment by wrathematics** [comment]
Thanks for the kind words. I'm a little surprised that updating the R version fixed the problem. We try to be fairly conservative about R features we adopt, and I thought 3.2.0 was accurate. I'll take a closer look.
