### ISSUE TITLE
Use remoter inside a script

### ISSUE THREAD

**Issue by lfdmotta** [RBigData/remoter#35]
Hi,

I have a very basic question. I'd like to write an R script that

1. Connects to a server using remoter client()
2. Executes some commands in the server etc.

However, if I write an R script called **myfile.R** as follows:

```
remoter:client( ... )
x = 1
```

Then if I try

```
source('myfile.R')
```

The result is that remoter is called and then the prompt shows, but the `x = 1` is not evaluated in the server. Rather, after exit() the x = 1 is executed.

Any ideas? What should I do to tell R to connect to the server and then wait for the remoter connection before executing the next line?

This also does not work:

```
con = remoter:client(...)

if(con) {
 x = 1
}
```

**Comment by wrathematics** [comment]
In the latest github version, there's a `batch()` function.  So you could create a script `myscript.R` that contained:

```r
x = 1
```

And then remotely execute it via:

```r
batch(file="myfile.R")
```

So it wort of works like `source()`, but for the remote machine. This way you don't have to modify the script; just modify the way it's called.

I've been planning to update this on CRAN for quite a while now, but there's a complicated chain of events that has to happen first and there have been a few hangups. I'm hoping we can get this release out to CRAN in a month or so.

**Comment by lfdmotta** [comment]
Thanks.
