### ISSUE TITLE
Issues with multiline statements

### ISSUE THREAD

**Issue by iagomez** [RBigData/remoter#36]
It looks like remoter struggles parsing multiline statements when the line contains quotation marks.
i.e
 This works
```
h<-hist(x, breaks=10, col="red", xlab="Miles Per Gallon",
       main="Histogram with Normal Curve")
```

But this fails:
```
stuff <- "some
text"
```
The following error is displayed:
```
remoter> stuff <- "some
Error: <text>:1:10: unexpected INCOMPLETE_STRING
1: stuff <- "some
            ^
remoter> text"
```

**Comment by wrathematics** [comment]
Thanks for the report! I believe this is now fixed in the latest version on github. If it's still broken for you, please feel free to re-open the issue.
