### ISSUE TITLE
Using remoter inside of Rmarkdown document

### ISSUE THREAD

**Issue by ckatsulis** [RBigData/remoter#38]
I am unable to use remoter to execute and retrieve data remotely inside of an R Markdown code block.  Does anyone have a suggestion on how to accomplish this task?

**Comment by wrathematics** [comment]
With the version on github (but not CRAN), you can use the `batch()` function. It accepts an R script as a file or character argument. Here's an example using the latter (client and server on the same machine for demonstration).

```
---
output: html_document
---

```{r}
x <- sample(1:10, size=3)
print(x)

script = 'c2s(x);sum(x)'
remoter::batch(script=script)
```

Here's a screenshot of an example output from knitting the document:
![rmd](https://user-images.githubusercontent.com/2561297/31030561-bf0acdfc-a523-11e7-8b5f-e53a7d40e03e.png)
