### ISSUE TITLE
rpng.off() issue

### ISSUE THREAD

**Issue by ryanknauber** [RBigData/remoter#40]
When trying to run a batch script, get the following error:

Error in if (get.status(need_auto_rpng_off)) auto_rpng_off_local(get.status(ret)) : 
  argument is of length zero

**Comment by apoorva007** [comment]
@ryanknauber See this :https://github.com/RBigData/remoter/issues/32
For me using the same version of package at both client and server helped.

**Comment by snoweye** [comment]
This should be fixed by using the same version of `remoter`. If not, please report a reproducible example. Thanks.
