### ISSUE TITLE
Will this allow me to use local RStudio but run R via SSH?

### ISSUE THREAD

**Issue by abalter** [RBigData/remoter#55]
This is a question, not an issue. But not sure where else to ask.

**Comment by wrathematics** [comment]
Nice avatar.

You can set up a remoter server on a remote machine and use the remoter client in your local RStudio. If you connect to your remote machine over ssh, you will need to forward the appropriate ports, which can be annoying. We've written about this a little [in this guide](https://cran.r-project.org/web/packages/remoter/vignettes/remote_machines.pdf), but the documentation is far from perfect.

**Comment by abalter** [comment]
Thanks :)

When you way "remote server" you just mean running `Rscript  -e "remoter :: server ()" &` on a remote server, NOT having rstudio server on a remote server. Is that correct? (too many servers!)

**Comment by wrathematics** [comment]
Right. If you have a remote machine that you have ssh access to, you can start the remoter server using just a command line R. You don't need any kind of graphical or web stuff installed.

You can test this locally by opening a terminal and running `Rscript -e "remoter::server(verbose=TRUE, showmsg=TRUE)"` in the terminal. This is the remoter server. Then in your RStudio session you can run `remoter::client()` to connect. You should see some connection information in the server window. If you type in commands in your RStudio window, they will be executed in the server's R process.

If you move the remoter server to another computer (say one you normally access by ssh), then starting the remoter server is basically the same. But connecting is a little more complicated. ssh tunnels may be the easiest route.

**Comment by snoweye** [comment]
You can also run R and SSH via [pbdRPC](https://github.com/RBigData/pbdRPC) to execute/shutdown server from local.
