### ISSUE TITLE
file '~' does not exist (in Windows)

### ISSUE THREAD

**Issue by wklink** [RBigData/remoter#9]
I can't load the package because the .onLoad fails.  The logfile_init has file_path_as_absolute("~") hard-coded, and that returns an error under Windows:

> library(remoter)
Error : .onLoad failed in loadNamespace() for 'remoter', details:
  call: tools::file_path_as_absolute("~")
  error: file '~' does not exist

**Comment by snoweye** [comment]
Try to get the fix from the pull request or from `github.com/snoweye/remoter`. Thanks for the report. Let us know if this problem does not go away.
